builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "go-yt-dlp-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=0
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1

archives:
  - format: binary
    name_template: "go-yt-dlp-{{ .Os }}-{{ .Arch }}"

release:
  draft: true
  replace_existing_draft: true
