builds:

  - goos:
      # - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "go-yt-dlp-{{ .Os }}-{{ .Arch }}"
    env:
      - CGO_ENABLED=1

archives:
  - format: binary
