name: build

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Make winres
        run: |
          go install github.com/tc-hib/go-winres@latest
          go-winres make

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: MacOS app bundle
        run: go run mac-bundle/main.go

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/go-yt-dlp_darwin_amd64_v1/go-yt-dlp-darwin-amd64,dist/go-yt-dlp_darwin_arm64/go-yt-dlp-darwin-arm64,dist/go-yt-dlp_windows_amd64_v1/go-yt-dlp-windows-amd64.exe,dist/go-yt-dlp_windows_arm64/go-yt-dlp-windows-arm64.exe"
          draft: true
          name: draft
          omitBody: true

      - name: Upload darwin arm64
        uses: actions/upload-artifact@v3
        with:
          name: go-yt-dlp darwin arm64
          path: dist/go-yt-dlp_darwin_arm64/*.app

      - name: Upload darwin amd64
        uses: actions/upload-artifact@v3
        with:
          name: go-yt-dlp darwin amd64
          path: dist/go-yt-dlp_darwin_amd64_v1/*.app

      # - name: Upload windows amd64
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: go-yt-dlp windows amd64
      #     path: dist/go-yt-dlp_windows_amd64_v1/go-yt-dlp.exe
